### ISSUE TITLE
App crash on startup on Android 4.4

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/template-master-detail-kinvey#52]
Create app from master branch of this template and update to latest packages:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.masterdetailkinvey",
    "tns-android": {
      "version": "4.0.0-2018.3.22.2"
    },
    "tns-ios": {
      "version": "4.0.1-2018-03-26-01"
    }
  },
  "scripts": {
    "lint": "eslint \"app/**/*.js\""
  },
  "dependencies": {
    "kinvey-nativescript-sdk": "3.9.7",
    "nativescript-imagepicker": "5.0.0",
    "nativescript-push-notifications": "1.0.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-ui-listview": "3.5.0",
    "tns-core-modules": "next"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "eslint": "4.9.0",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.5",
    "nativescript-dev-webpack": "0.10.0-2018-04-02-01",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}
```
App crash on startup on Android 4.4 (it is fine on 6.0).

Logcat:
```
--------- beginning of /dev/log/system
I/ActivityManager( 1566): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.nativescript.masterdetailkinvey/com.tns.NativeScriptActivity} from pid 1881
D/dalvikvm( 1566): GC_CONCURRENT freed 334K, 30% free 9489K/13484K, paused 3ms+1ms, total 12ms
D/gralloc_ranchu( 1142): gralloc_alloc: Creating ashmem region of size 1536000
D/dalvikvm( 2280): Not late-enabling CheckJNI (already on)
I/ActivityManager( 1566): Start proc org.nativescript.masterdetailkinvey for activity org.nativescript.masterdetailkinvey/com.tns.NativeScriptActivity: pid=2280 uid=10052 gids={50052, 1028, 1015, 3003}
D/AndroidRuntime( 2280): Shutting down VM
W/dalvikvm( 2280): threadid=1: thread exiting with uncaught exception (group=0xacd27b20)
E/AndroidRuntime( 2280): FATAL EXCEPTION: main
E/AndroidRuntime( 2280): Process: org.nativescript.masterdetailkinvey, PID: 2280
E/AndroidRuntime( 2280): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.nativescript.masterdetailkinvey-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.masterdetailkinvey-1, /system/lib]]
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 2280): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2280): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2280): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2280): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2280): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2280): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2280): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2280): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.nativescript.masterdetailkinvey-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.nativescript.masterdetailkinvey-1, /system/lib]]
E/AndroidRuntime( 2280): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 2280): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime( 2280): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime( 2280): 	at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
E/AndroidRuntime( 2280): 	... 12 more
W/ActivityManager( 1566):   Force finishing activity org.nativescript.masterdetailkinvey/com.tns.NativeScriptActivity
D/EGL_emulation( 1881): eglMakeCurrent: 0xb7bc3420: ver 3 0
D/gralloc_ranchu( 1142): gralloc_alloc: Creating ashmem region of size 405504
D/        ( 1566): HostConnection::get() New Host Connection established 0xb7e299e0, tid 1578
D/gralloc_ranchu( 1142): gralloc_alloc: Creating ashmem region of size 430080
W/ActivityManager( 1566): Activity pause timeout for ActivityRecord{ad2a9518 u0 org.nativescript.masterdetailkinvey/com.tns.NativeScriptActivity t5 f}
D/EGL_emulation( 1881): eglMakeCurrent: 0xb7bc3420: ver 3 0
D/gralloc_ranchu( 1142): gralloc_alloc: Creating ashmem region of size 430080
D/gralloc_ranchu( 1142): gralloc_alloc: Creating ashmem region of size 430080
```

Same happens on TS flavour of this template, while NG flavour is ok.

**Comment by vtrifonov** [comment]
This issue was moved to NativeScript/android-runtime#999
